wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.8
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691522137.379535
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 6
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.8
      5: 0.15.8
      8:
      - 5
      - 9
