wandb_version: 1

predictor:
  desc: null
  value: cpu_predictor
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.8
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690926913.269575
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      - 105
      2:
      - 5
      - 6
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      - 31
      4: 3.10.8
      5: 0.15.8
      8:
      - 5
